name: kamchatka
description: "LCT2024"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  google_fonts: ^6.2.0
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  yandex_mapkit: ^4.0.2
  form_inputs:
    path: packages/form_inputs
  numberpicker: ^2.1.2
  flutter_holo_date_picker: ^1.1.3
  intl: ^0.19.0
  flutter_secure_storage: ^4.2.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.3
  collection: ^1.18.0
  custom_radio_grouped_button: ^2.2.1
  json_serializable: ^6.8.0
  file_picker: ^8.0.5
  path: ^1.9.0
  flutter_launcher_icons: ^0.13.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_gen: ^5.5.0+1
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0

flutter_gen:
  integrations: 
    flutter_svg: true
  output: lib/gen/
  colors:
    inputs:
      - assets/colors.xml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_gravity: fill
  android_12: 
    color: "#FFFFFF"
    image: assets/images/splash.png
    android_gravity: fill

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/auth/
    - assets/
